name: ci

on: [push, pull_request]

jobs:
  send_message_1:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 1/3 ${{ github.repository }} start!

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image ml
        run: docker build -f=Dockerfile -t yutfut/ml:${GITHUB_SHA::8} .

      - name: Push the image ml
        run: docker push yutfut/ml:${GITHUB_SHA::8}

  send_message_2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 2/3 ${{ github.repository }} build done!

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd infrastructure/
            sudo docker-compose stop
            sudo docker-compose down
            df -h
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker rmi -f $(sudo docker images -a yutfut/ml)
            df -h
            echo ML_VERSION=${GITHUB_SHA::8} >> .env
            sudo docker-compose up -d
            df -h

  send_message_3:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:  |
            3/3 ${{ github.repository }} successes!
            -*//*- https://study-ai.ru -*//*-